# __    __          _           _
#/ / /\ \ \__ _  __| |_ __ ___ (_)_ __
#\ \/  \/ / _` |/ _` | '_ ` _ \| | '_ \
# \  /\  / (_| | (_| | | | | | | | | | |
#  \/  \/ \__,_|\__,_|_| |_| |_|_|_| |_|

#                            Webhook settings
# Paste the webhook URL here
webhook: "webhook_here"



#                            Creeper Command
# Webhook message for /wadmin creeper command
webhook_creeper: "%target% got %amount% creeper by %executor%"
# Message format when a player executes the /wadmin creeper command
creeper_msg: "§4%target% got %amount% creeper"
# Default amount of creeper for players when using the /wadmin creeper command
default_creeper: 5



#                            TNT Command
# Webhook message for /wadmin tnt command
webhook_tnt: "%target% got %amount% tnt by %executor%"
# Message format when a player executes the /wadmin tnt command
tnt_msg: "§4%target% got %amount% tnt"
# Default amount of TNT for players when using the /wadmin tnt command
default_tnt: 5



#                            Clear Command
# Webhook message for /wadmin clear command
webhook_clear: "%target% got cleared by %executor%"
# Message format when a player executes the /wadmin clear command
clear_msg: "§4%target% got cleared"



#                            Kill Command
# Webhook message for /wadmin kill command
webhook_kill: "%target% killed by %executor%"
# Message format when a player executes the /wadmin kill command
kill_msg: "§4%target% killed"



#                            Air Command
# Webhook message for /wadmin air command
webhook_air: "%target% sent to the air by %executor%"
# Message format when a player executes the /wadmin air command
air_msg: "§4%target% sent to the air"



#                            Explode Command
# Webhook message for /wadmin explode command
webhook_explode: "%target% exploded by %executor%"
# Message format when a player executes the /wadmin explode command
explode_msg: "§4%target% exploded"



#                            Slow Command
# Webhook message for slowness activation
webhook_slow_on: "%target% now slow by %executor%"
# Webhook message for slowness deactivation
webhook_slow_off: "%target% now not slow by %executor%"
# Message format when a player activates the slowness
slow_msg_on: "§4%target% now slow"
# Message format when a player deactivates the slowness
slow_msg_off: "§2%target% now not slow"



#                            Error Messages
# Message when player is not specified for a command
non_specified_player: "§cPlease specify a player"
# Message when specified player is not found
player_not_found: "§cPlayer not found"



#                            Join messages
# Message displayed when a player joins
join_msg: "§6Wadmin is on KYS"
