#                            Wtroll Plugin
#                            Webhook settings
# Paste the webhook URL here
webhook: "webhook_here"



#                            Creeper Command
# Webhook message for /wtroll creeper command
webhook_creeper: "%target% got %amount% creeper by %executor%"
# Message format when a player executes the /wtroll creeper command
creeper_msg: "§4%target% got %amount% creeper"
# Default amount of creeper for players when using the /wtroll creeper command
default_creeper: 5



#                            TNT Command
# Webhook message for /wtroll tnt command
webhook_tnt: "%target% got %amount% tnt by %executor%"
# Message format when a player executes the /wtroll tnt command
tnt_msg: "§4%target% got %amount% tnt"
# Default amount of TNT for players when using the /wtroll tnt command
default_tnt: 5



#                            Clear Command
# Webhook message for /wtroll clear command
webhook_clear: "%target% got cleared by %executor%"
# Message format when a player executes the /wtroll clear command
clear_msg: "§4%target% got cleared"



#                            Kill Command
# Webhook message for /wtroll kill command
webhook_kill: "%target% killed by %executor%"
# Message format when a player executes the /wtroll kill command
kill_msg: "§4%target% killed"



#                            Air Command
# Webhook message for /wtroll air command
webhook_air: "%target% sent to the air by %executor%"
# Message format when a player executes the /wtroll air command
air_msg: "§4%target% sent to the air"



#                            Explode Command
# Webhook message for /wtroll explode command
webhook_explode: "%target% exploded by %executor%"
# Message format when a player executes the /wtroll explode command
explode_msg: "§4%target% exploded"



#                            Slow Command
# Webhook message for slowness activation
webhook_slow_on: "%target% now slow by %executor%"
# Webhook message for slowness deactivation
webhook_slow_off: "%target% now not slow by %executor%"
# Message format when a player activates the slowness
slow_msg_on: "§4%target% now slow"
# Message format when a player deactivates the slowness
slow_msg_off: "§2%target% now not slow"

#                            Demo Command
# Webhook message for /wtroll demo command
webhook_demo: "%target% forced to buy mineraft by %executor%"
# Message format when a player executes the /wtroll demo command
demo_msg: "§4%target% bought minecraft"

#                            Endgame Command
# Webhook message for /wtroll endgame command
webhook_endgame: "%target% forced to buy mineraft %executor%"
# Message format when a player executes the /wtroll demo command
endgame_msg: "§4%target% completed the game"

#                            Noescape Command
# Webhook message for /wtroll noescape command
webhook_noescape: "%target% stuck in a loading screen by  %executor%"
# Message format when a player executes the /wtroll noescape command
noescape_msg: "§4%target% stuck in a loading screen"

#                            Lookdown Command
# Webhook message for /wtroll lookdown command
webhook_lookdown: "%target% now facing down by  %executor%"
# Message format when a player executes the /wtroll lookdown command
lookdown_msg: "§4%target% found a coin"

#                            Lookdown Command
# Webhook message for /wtroll lookup command
webhook_lookup: "%target% now facing up by  %executor%"
# Message format when a player executes the /wtroll lookup command
lookup_msg: "§4%target% seen a bird"



#                            Error Messages
# Message when player is not specified for a command
non_specified_player: "§cPlease specify a player"
# Message when specified player is not found
player_not_found: "§cPlayer not found"



#                            Join messages
# Message displayed when a player joins
join_msg: "§6I love you "
