# __    __          _           _
#/ / /\ \ \__ _  __| |_ __ ___ (_)_ __
#\ \/  \/ / _` |/ _` | '_ ` _ \| | '_ \
# \  /\  / (_| | (_| | | | | | | | | | |
#  \/  \/ \__,_|\__,_|_| |_| |_|_|_| |_|

#webhook
webhook: "webhook_here"

#webhook messages

webhook_creeper: "%target% lol %amount% lol %executor%"
webhook_clear: "%target% lol %executor%"
webhook_kill: "%target% lol %executor%"
webhook_tnt: "%target% lol %amount% lol %executor%"
webhook_air: "%target% lol %executor%"
webhook_explode: "%target% lol %executor%"

# Error Messages
non_specified_player: "§cPlease specify a player"
player_not_found: "§cPlayer not found"

# Event Messages
creeper_msg: "%target% lol %amount%"
clear_msg: "%target% lol "
kill_msg: "%target% lol "
tnt_msg: "%target% lol %amount%"
air_msg: "%target% lol "
explode_msg: "%target% lol "

# Default Values
default_tnt: 5
default_creeper: 5
