name: Wadmin
version: '1.0.0-alpha'
author: Dzsivokado
main: dzsivokado.elsonormalpluginom.Wadmin
api-version: '1.18'
commands:
  #teszt:
    #description: "gg"
  wtroll:
    description: "a Wadmin plugin"
    usage:
      - "/wadmin creeper <player> <amount>"
      - "/wadmin tnt <player> <amount>"
      - "/wadmin clear <player>"
      - "/wadmin kill <player>"
      - "/wadmin explode <player>"
      - "/wadmin air <player>"
      - "/wadmin slow <player>"
permissions:
  wadmin.*:
    description: "wadmin commands"
    children:
      - wadmin.creeper: true
      - wadmin.tnt: true
      - wadmin.clear: true
      - wadmin.kill: true
      - wadmin.explode: true
      - wadmin.air: true
      - wadmin.slow: true
  wadmin.tnt:
    description: "wadmin tnt"
  wadmin.creeper:
    description: "wadmin creeper"
  wadmin.clear:
    description: "wadmin clear"
  wadmin.kill:
    description: "wadmin kill"
  wadmin.explode:
    description: "wadmin explode"
  wadmin.air:
    description: "wadmin air"
  wadmin.slow:
    description: "wadmin slow"