name: Wadmin
version: '1.0.0-alpha'
author: Dzsivokado
main: dzsivokado.elsonormalpluginom.Wadmin
api-version: '1.18'
commands:
  wadmin:
    description: "a Wadmin plugin"
    usage:
      - "/wadmin creeper <player> <amount>"
      - "/wadmin tnt <player> <amount>"
      - "/wadmin clear <player>"
      - "/wadmin kill <player>"
      - "/wadmin explode <player>"
      - "/wadmin air <player>"
    permission: "wadmin.wadmin"
  teszt:
    usage: "teszt"