name: Wtroll
version: '1.0.0-alpha'
author: Dzsivokado
main: dzsivokado.elsonormalpluginom.Wtroll
api-version: '1.18'
commands:
  #teszt:
    #description: "gg"
  wtroll:
    description: "a wtroll plugin"
    usage:
      - "/wtroll creeper <player> <amount>"
      - "/wtroll tnt <player> <amount>"
      - "/wtroll clear <player>"
      - "/wtroll kill <player>"
      - "/wtroll explode <player>"
      - "/wtroll air <player>"
      - "/wtroll slow <player>"
permissions:
  wtroll.*:
    description: "wtroll commands"
    children:
      - wtroll.creeper: true
      - wtroll.tnt: true
      - wtroll.clear: true
      - wtroll.kill: true
      - wtroll.explode: true
      - wtroll.air: true
      - wtroll.slow: true
  wtroll.tnt:
    description: "wtroll tnt"
  wtroll.creeper:
    description: "wtroll creeper"
  wtroll.clear:
    description: "wtroll clear"
  wtroll.kill:
    description: "wtroll kill"
  wtroll.explode:
    description: "wtroll explode"
  wtroll.air:
    description: "wtroll air"
  wtroll.slow:
    description: "wtroll slow"